
import type { MenuItem, Review, NavLink } from './types';

export const NAV_LINKS: NavLink[] = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'menu', label: 'Menu' },
  { id: 'gallery', label: 'Gallery' },
  { id: 'contact', label: 'Contact' },
];

export const MENU_ITEMS: MenuItem[] = [
  // Dosa (SLOT 1)
  { id: 1, name: 'Plain Dosa', price: 119, category: 'Dosa', description: 'A classic crispy and savory crepe made from fermented rice and lentil batter.', image: '/images/menu/slot-1/PLAIN-DOSA (2).png' },
  { id: 2, name: 'Masala Dosa', price: 139, category: 'Dosa', description: 'A crispy dosa stuffed with a flavorful spiced potato filling.', image: '/images/menu/slot-1/masala-dosa.png' },
  { id: 3, name: 'Beetroot Dosa', price: 159, category: 'Dosa', description: 'A vibrant and healthy dosa with the wholesome goodness of beetroot.', image: '/images/menu/slot-1/beetroot-dosa.png' },
  { id: 4, name: 'Mysore Plain Dosa', price: 159, category: 'Dosa', description: 'A classic dosa layered with a spicy red chutney for an extra kick.', image: '/images/menu/slot-1/RAWA-MYSORE-PLAIN-DOSA.png' },
  { id: 5, name: 'Onion Masala Dosa', price: 159, category: 'Dosa', description: 'A delicious variation with sauteed onions and a savory potato masala.', image: '/images/menu/slot-1/ONION-MASALA-DOSA.png' },
  { id: 6, name: 'Mysore Masala Dosa', price: 169, category: 'Dosa', description: 'Features a spicy chutney spread and a savory potato filling.', image: '/images/menu/slot-1/mysore-masala-dosa.png' },
  { id: 7, name: 'Butter Masala Dosa', price: 169, category: 'Dosa', description: 'A rich and indulgent dosa cooked with a generous amount of butter.', image: '/images/menu/slot-1/BUTTER-MASALA-DOSA.png' },
  { id: 8, name: 'Ghee Roast Plain Dosa', price: 169, category: 'Dosa', description: 'A plain dosa roasted to perfection with aromatic clarified butter (ghee).', image: '/images/menu/slot-1/ghee-roast-dosa.png' },
  { id: 9, name: 'Podi Masala Dosa', price: 169, category: 'Dosa', description: 'Dosa coated with a flavorful and aromatic spiced powder (podi).', image: '/images/menu/slot-1/PODI-MASALA-DOSA.png' },
  { id: 10, name: 'Rawa Mysore Plain Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa with a layer of spicy Mysore chutney.', image: '/images/menu/slot-1/RAWA-MYSORE-PLAIN-DOSA.png' },
  { id: 11, name: 'Rawa Ghee Roast Plain Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa roasted with fragrant ghee.', image: '/images/menu/slot-1/RAWA-GHEE-ROAST-PLAIN-DOSA.png' },
  { id: 12, name: 'Rawa Masala Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa with a spiced potato filling.', image: '/images/menu/slot-1/RAWA-MASALA-DOSA.png' },
  { id: 13, name: 'Cheese Masala Dosa', price: 179, category: 'Dosa', description: 'A cheesy twist on the classic masala dosa, loved by all ages.', image: '/images/menu/slot-1/CHEESE-MASALA-D0SA.png' },
  { id: 14, name: 'Ghee Roast Masala Dosa', price: 179, category: 'Dosa', description: 'A masala dosa roasted with ghee for a rich, aromatic flavor.', image: '/images/menu/slot-1/GHEE-ROAST-MASALA-DOSA.png' },
  { id: 15, name: 'Rawa Mysore Masala Dosa', price: 179, category: 'Dosa', description: 'Crispy semolina dosa with spicy chutney and potato filling.', image: '/images/menu/slot-1/RAWA-MYSORE-MASALA-DOSA.png' },
  { id: 16, name: 'Rawa Onion Masala Dosa', price: 179, category: 'Dosa', description: 'Semolina dosa with onions and a spiced potato filling.', image: '/images/menu/slot-1/RAWA-ONION-MASALA-DOSA.png' },
  { id: 17, name: 'Rawa Paneer Masala Dosa', price: 179, category: 'Dosa', description: 'A semolina dosa filled with spiced cottage cheese (paneer).', image: '/images/menu/slot-1/RAWA-PANEER-MASALA-DOSA.png' },
  { id: 18, name: 'Rawa Ghee Roast Masala Dosa', price: 179, category: 'Dosa', description: 'Crispy semolina dosa with potato filling, roasted in ghee.', image: '/images/menu/slot-1/RAWA-GHEE-ROAST-MASALA-DOSA.png' },
  { id: 19, name: 'Paneer Masala Dosa', price: 189, category: 'Dosa', description: 'A classic dosa with a delicious spiced paneer filling.', image: '/images/menu/slot-1/PANEER-MASALA-DOSA.png' },
  { id: 20, name: 'Paper Masala Dosa', price: 249, category: 'Dosa', description: 'An extra-large, paper-thin and crispy dosa with a side of masala.', image: '/images/menu/slot-1/masala-dosa.png' },
  { id: 21, name: 'Mini Dosa Platter', price: 299, category: 'Dosa', description: 'An assortment of our popular mini dosas, perfect for trying a bit of everything.', image: '/images/menu/slot-1/MINI-DOSA-PLATTER.png' },
  
  // Srivalli Special Dosa (SLOT 2)
  { id: 22, name: 'Patta Dosa', price: 189, category: 'Srivalli Special Dosa', description: 'A unique and flavorful dosa shaped like a leaf, a true specialty.', image: '/images/menu/slot-2/patta-dosa.png' },
  { id: 23, name: 'Palak Paneer Dosa', price: 189, category: 'Srivalli Special Dosa', description: 'A healthy and delicious dosa with a creamy spinach and paneer filling.', image: '/images/menu/slot-2/PALAK-PANEER-DOSA.png' },
  { id: 24, name: 'Peri-Peri Cheese Dosa', price: 219, category: 'Srivalli Special Dosa', description: 'A spicy and cheesy fusion dosa for the adventurous palate.', image: '/images/menu/slot-2/PERI-PERI-CHEESE-DOSA.png' },
  { id: 25, name: 'Paneer Cheese Surma', price: 219, category: 'Srivalli Special Dosa', description: 'A rich and savory dosa with a blend of paneer and cheese.', image: '/images/menu/slot-2/PANEER-CHEESE-SURMA.png' },
  { id: 26, name: 'Paneer Tikka Dosa', price: 219, category: 'Srivalli Special Dosa', description: 'A dosa filled with smoky and spicy tandoori paneer tikka.', image: '/images/menu/slot-2/PANEER-TIKKA-DOSA.png' },
  { id: 27, name: 'Cheese Burst Dosa', price: 229, category: 'Srivalli Special Dosa', description: 'An indulgent dosa loaded with molten, gooey cheese.', image: '/images/menu/slot-2/cheese-burst-dosa.png' },
  { id: 28, name: 'Cheese Corn Dosa', price: 229, category: 'Srivalli Special Dosa', description: 'A delightful combination of sweet corn and savory cheese in a crispy dosa.', image: '/images/menu/slot-2/CHEESE-CORN-DOSA.png' },
  { id: 29, name: 'Pizza Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'An exciting fusion of Italian pizza toppings on a South Indian dosa base.', image: '/images/menu/slot-2/PIZZA-DOSA (2).png' },
  { id: 30, name: 'Jinni Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A popular Mumbai-style dosa loaded with vegetables and cheese.', image: '/images/menu/slot-2/JINNI-DOSA.png' },
  { id: 31, name: 'Dilkhoosh Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A special sweet and savory dosa that is sure to delight your taste buds.', image: '/images/menu/slot-2/DILKHOOSH-DOSA.png' },
  { id: 32, name: 'Pasta Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A creative fusion dish combining Italian pasta and a South Indian dosa.', image: '/images/menu/slot-2/PASTA-DOSA (2).png' },
  { id: 33, name: 'Manchurian Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'An Indo-Chinese delight with a tangy Manchurian filling in a crispy dosa.', image: '/images/menu/slot-2/MANCHURIAN-DOSA.png' },
  { id: 34, name: 'Noodles Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A unique dosa filled with flavorful stir-fried noodles.', image: '/images/menu/slot-2/NOODLES-DOSA.png' },
  { id: 35, name: 'Srivalli Family Dosa', price: 349, category: 'Srivalli Special Dosa', description: 'A giant, shareable dosa perfect for families and groups.', image: '/images/menu/slot-2/SRIVALLI-FAMILY-DOSA.png' },

  // Uttapam & Upma
  { id: 36, name: 'Plain Uttapam', price: 149, category: 'Uttapam & Upma', description: 'A thick, savory pancake made from rice batter, soft and fluffy.', image: '/images/menu/item-36.jpg' },
  { id: 37, name: 'Onion Uttapam', price: 159, category: 'Uttapam & Upma', description: 'A savory uttapam topped with finely chopped, flavorful onions.', image: '/images/menu/item-37.jpg' },
  { id: 38, name: 'Coconut Uttapam', price: 169, category: 'Uttapam & Upma', description: 'A delicious uttapam topped with fresh, grated coconut.', image: '/images/menu/item-38.jpg' },
  { id: 39, name: 'Onion Tomato Uttapam', price: 169, category: 'Uttapam & Upma', description: 'A classic combination of onions and tomatoes on a soft uttapam.', image: '/images/menu/item-39.jpg' },
  { id: 40, name: 'Mixed Veg Uttapam', price: 179, category: 'Uttapam & Upma', description: 'A wholesome uttapam loaded with a variety of fresh vegetables.', image: '/images/menu/item-40.jpg' },
  { id: 41, name: 'Paneer Tikka Uttapam', price: 189, category: 'Uttapam & Upma', description: 'A fusion uttapam topped with spicy and smoky paneer tikka.', image: '/images/menu/item-41.jpg' },
  { id: 42, name: 'Mini Uttapam Platter', price: 299, category: 'Uttapam & Upma', description: 'An assortment of our popular mini uttapams.', image: '/images/menu/item-42.jpg' },
  { id: 43, name: 'Vegetable Upma', price: 129, category: 'Uttapam & Upma', description: 'A savory porridge made from semolina and mixed vegetables.', image: '/images/menu/item-43.jpg' },
  { id: 44, name: 'Paneer vegetable Upma', price: 159, category: 'Uttapam & Upma', description: 'A protein-rich upma with added cottage cheese and vegetables.', image: '/images/menu/item-44.jpg' },

  // Idli & Srivalli Special Dishes
  { id: 45, name: 'Steam Idli', price: 79, category: 'Idli & Srivalli Special Dishes', description: 'Soft, fluffy steamed rice cakes, a South Indian staple.', image: '/images/menu/item-45.jpg' },
  { id: 46, name: 'Mini Idli', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Bite-sized idlis, perfect for a light snack or appetizer.', image: '/images/menu/item-46.jpg' },
  { id: 47, name: 'Medu Vada', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and savory deep-fried lentil doughnuts.', image: '/images/menu/item-47.jpg' },
  { id: 48, name: 'Idli Chaat', price: 99, category: 'Idli & Srivalli Special Dishes', description: 'A tangy and spicy snack made with idli, chutneys, and yogurt.', image: '/images/menu/item-48.jpg' },
  { id: 49, name: 'White Sauce Idli', price: 119, category: 'Idli & Srivalli Special Dishes', description: 'A fusion dish with idlis tossed in a creamy white sauce.', image: '/images/menu/item-49.jpg' },
  { id: 50, name: 'Sejwan Idli', price: 129, category: 'Idli & Srivalli Special Dishes', description: 'Spicy idlis tossed in a fiery Schezwan sauce.', image: '/images/menu/item-50.jpg' },
  { id: 51, name: 'Chinese Idli', price: 149, category: 'Idli & Srivalli Special Dishes', description: 'An Indo-Chinese style dish with crispy fried idlis.', image: '/images/menu/item-51.jpg' },
  { id: 52, name: 'Puri Bhaaji', price: 69, category: 'Idli & Srivalli Special Dishes', description: 'Fluffy deep-fried bread served with a savory potato curry.', image: '/images/menu/item-52.jpg' },
  { id: 53, name: 'Appey', price: 79, category: 'Idli & Srivalli Special Dishes', description: 'Small, round, savory pancakes that are crispy on the outside and soft inside.', image: '/images/menu/item-53.jpg' },
  { id: 54, name: 'Idli pakoda', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and delicious deep-fried idli fritters.', image: '/images/menu/item-54.jpg' },
  { id: 55, name: 'Thaate Idli', price: 99, category: 'Idli & Srivalli Special Dishes', description: 'A large, plate-sized idli that is exceptionally soft and fluffy.', image: '/images/menu/item-55.jpg' },
  { id: 56, name: 'Ghee Podi Idli', price: 109, category: 'Idli & Srivalli Special Dishes', description: 'Mini idlis tossed in fragrant ghee and aromatic spiced powder.', image: '/images/menu/item-56.jpg' },
  { id: 57, name: 'Dal Vada', price: 109, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and savory deep-fried lentil fritters.', image: '/images/menu/item-57.jpg' },
  { id: 58, name: 'Potato Bonda with Chutney', price: 119, category: 'Idli & Srivalli Special Dishes', description: 'Spiced potato balls coated in batter and deep-fried to perfection.', image: '/images/menu/item-58.jpg' },
  { id: 59, name: 'Rasam Papadarn', price: 129, category: 'Idli & Srivalli Special Dishes', description: 'A tangy and spicy South Indian soup served with crispy papad.', image: '/images/menu/item-59.jpg' },
  { id: 60, name: 'Fried Idli', price: 149, category: 'Idli & Srivalli Special Dishes', description: 'Crispy fried idli cubes tossed with spices.', image: '/images/menu/item-60.jpg' },
  
  // Agra Chat & Pizza
  { id: 61, name: 'Pani Puri', price: 19, category: 'Agra Chat & Pizza', description: 'Hollow crispy balls filled with a tangy and spicy mint water.', image: '/images/menu/item-61.jpg' },
  { id: 62, name: 'Sev Puri', price: 39, category: 'Agra Chat & Pizza', description: 'Flat crispy discs topped with potatoes, chutneys, and crunchy sev.', image: '/images/menu/item-62.jpg' },
  { id: 63, name: 'Aloo Chat', price: 49, category: 'Agra Chat & Pizza', description: 'A tangy and spicy snack made with fried potatoes and chutneys.', image: '/images/menu/item-63.jpg' },
  { id: 64, name: 'Masala Papad', price: 49, category: 'Agra Chat & Pizza', description: 'A crispy papad topped with onions, tomatoes, and spices.', image: '/images/menu/item-64.jpg' },
  { id: 65, name: 'Dahi Vada', price: 49, category: 'Agra Chat & Pizza', description: 'Soft lentil dumplings soaked in creamy yogurt and topped with chutneys.', image: '/images/menu/item-65.jpg' },
  { id: 66, name: 'Wada Pav', price: 49, category: 'Agra Chat & Pizza', description: 'Mumbai\'s iconic street food, a spiced potato fritter in a soft bun.', image: '/images/menu/item-66.jpg' },
  { id: 67, name: 'Mumbai Bhel Puri', price: 59, category: 'Agra Chat & Pizza', description: 'A savory snack made with puffed rice, vegetables, and tangy tamarind sauce.', image: '/images/menu/item-67.jpg' },
  { id: 68, name: 'Papri Chat', price: 69, category: 'Agra Chat & Pizza', description: 'A popular street food snack with crispy wafers, potatoes, and chutneys.', image: '/images/menu/item-68.jpg' },
  { id: 69, name: 'Fruit Chat', price: 69, category: 'Agra Chat & Pizza', description: 'A refreshing and healthy snack made with a mix of fresh fruits and spices.', image: '/images/menu/item-69.jpg' },
  { id: 70, name: 'Chana Chat', price: 79, category: 'Agra Chat & Pizza', description: 'A protein-packed and flavorful salad made with chickpeas.', image: '/images/menu/item-70.jpg' },
  { id: 71, name: 'Pav Bhaji', price: 89, category: 'Agra Chat & Pizza', description: 'A hearty dish of mashed vegetable curry served with soft, buttery buns.', image: '/images/menu/item-71.jpg' },
  { id: 72, name: 'Aloo Tiki', price: 99, category: 'Agra Chat & Pizza', description: 'Spiced potato patties, shallow-fried until golden and crisp.', image: '/images/menu/item-72.jpg' },
  { id: 73, name: 'Paneer Chilla', price: 99, category: 'Agra Chat & Pizza', description: 'A savory pancake made from gram flour, filled with spiced paneer.', image: '/images/menu/item-73.jpg' },
  { id: 74, name: 'Dry Fruit Chat', price: 99, category: 'Agra Chat & Pizza', description: 'A rich and healthy chaat made with a mix of dry fruits and nuts.', image: '/images/menu/item-74.jpg' },
  { id: 75, name: 'Chole Bhature', price: 109, category: 'Agra Chat & Pizza', description: 'A classic North Indian dish of fluffy fried bread with a spicy chickpea curry.', image: '/images/menu/item-75.jpg' },
  { id: 76, name: 'Onion Pizza', price: 139, category: 'Agra Chat & Pizza', description: 'A simple yet delicious pizza topped with fresh onions and cheese.', image: '/images/menu/item-76.jpg' },
  { id: 77, name: 'Corn Pizza', price: 159, category: 'Agra Chat & Pizza', description: 'A tasty pizza topped with sweet corn and mozzarella cheese.', image: '/images/menu/item-77.jpg' },
  { id: 78, name: 'OTC Pizza', price: 169, category: 'Agra Chat & Pizza', description: 'A flavorful pizza with onion, tomato, and capsicum toppings.', image: '/images/menu/item-78.jpg' },
  { id: 79, name: 'Margherita Pizza', price: 169, category: 'Agra Chat & Pizza', description: 'A classic pizza with tomato sauce, mozzarella cheese, and fresh basil.', image: '/images/menu/item-79.jpg' },
  { id: 80, name: 'Tandoori Paneer Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'An Indian-style pizza with marinated tandoori paneer.', image: '/images/menu/item-80.jpg' },
  { id: 81, name: 'Peppy Paneer Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'A spicy and flavorful pizza with paneer and zesty peppers.', image: '/images/menu/item-81.jpg' },
  { id: 82, name: 'Farmhouse Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'A wholesome pizza loaded with a variety of fresh farm vegetables.', image: '/images/menu/item-82.jpg' },
  
  // Chinese
  { id: 83, name: 'Momos', price: 50, category: 'Chinese', description: 'Steamed dumplings filled with a savory vegetable stuffing.', image: '/images/menu/item-83.jpg' },
  { id: 84, name: 'Plain Maggi', price: 70, category: 'Chinese', description: 'A classic comfort food, instant noodles cooked to perfection.', image: '/images/menu/item-84.jpg' },
  { id: 85, name: 'Veg Spring Roll', price: 99, category: 'Chinese', description: 'Crispy fried rolls filled with a delicious vegetable stuffing.', image: '/images/menu/item-85.jpg' },
  { id: 86, name: 'Masala Maggi', price: 100, category: 'Chinese', description: 'Instant noodles cooked with a flavorful blend of Indian spices.', image: '/images/menu/item-86.jpg' },
  { id: 87, name: 'Chowmein Roll', price: 109, category: 'Chinese', description: 'A tasty roll stuffed with stir-fried noodles and vegetables.', image: '/images/menu/item-87.jpg' },
  { id: 88, name: 'Fried Rice', price: 120, category: 'Chinese', description: 'A classic Indo-Chinese dish of stir-fried rice with vegetables.', image: '/images/menu/item-88.jpg' },
  { id: 89, name: 'Veg Crispy', price: 129, category: 'Chinese', description: 'Crispy fried vegetables tossed in a tangy and spicy sauce.', image: '/images/menu/item-89.jpg' },
  { id: 90, name: 'Hakka Noodles', price: 130, category: 'Chinese', description: 'Stir-fried noodles with a mix of vegetables and savory sauces.', image: '/images/menu/item-90.jpg' },
  { id: 91, name: 'Veg. Noodles', price: 130, category: 'Chinese', description: 'A simple yet delicious dish of stir-fried noodles with vegetables.', image: '/images/menu/item-91.jpg' },
  { id: 92, name: 'Manchurian Dry', price: 130, category: 'Chinese', description: 'Deep-fried vegetable balls tossed in a tangy and savory sauce.', image: '/images/menu/item-92.jpg' },
  { id: 93, name: 'Manchurian Gravy', price: 130, category: 'Chinese', description: 'Vegetable balls in a flavorful and tangy gravy.', image: '/images/menu/item-93.jpg' },
  { id: 94, name: 'American Chopsy', price: 139, category: 'Chinese', description: 'A delightful dish of crispy noodles topped with a sweet and tangy vegetable sauce.', image: '/images/menu/item-94.jpg' },
  { id: 95, name: 'Chinese Bhel', price: 139, category: 'Chinese', description: 'A fusion snack made with crispy noodles, vegetables, and tangy sauces.', image: '/images/menu/item-95.jpg' },
  { id: 96, name: 'Chilli Potato', price: 139, category: 'Chinese', description: 'Crispy fried potatoes tossed in a spicy and tangy chili sauce.', image: '/images/menu/item-96.jpg' },
  { id: 97, name: 'Chilli Paneer Dry', price: 150, category: 'Chinese', description: 'A popular Indo-Chinese dish of fried paneer tossed in a spicy sauce.', image: '/images/menu/item-97.jpg' },
  { id: 98, name: 'Chilli Paneer Gravy', price: 150, category: 'Chinese', description: 'Fried paneer in a flavorful and spicy gravy.', image: '/images/menu/item-98.jpg' },
  { id: 99, name: 'Honey Chilli Potato', price: 159, category: 'Chinese', description: 'A sweet and spicy dish of crispy fried potatoes coated in honey chili sauce.', image: '/images/menu/item-99.jpg' },
  { id: 100, name: 'Red Sauce Pasta', price: 179, category: 'Chinese', description: 'A classic Italian pasta dish in a tangy tomato-based sauce.', image: '/images/menu/item-100.jpg' },
  { id: 101, name: 'White Sauce Pasta', price: 189, category: 'Chinese', description: 'A creamy and delicious pasta dish in a rich white sauce.', image: '/images/menu/item-101.jpg' },
  { id: 102, name: 'French Fries', price: 100, category: 'Chinese', description: 'Classic crispy and golden deep-fried potato strips.', image: '/images/menu/item-102.jpg' },
  
  // Breakfast (Tea, Sandwich, Soup, Burger)
  { id: 103, name: 'Tea', price: 20, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A refreshing cup of hot tea to start your day.', image: '/images/menu/item-103.jpg' },
  { id: 104, name: 'Tomato Soup', price: 49, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic and comforting soup made with fresh tomatoes.', image: '/images/menu/item-104.jpg' },
  { id: 105, name: 'Classic Burger', price: 50, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A simple and delicious burger with a vegetable patty.', image: '/images/menu/item-105.jpg' },
  { id: 106, name: 'Cheese Burger', price: 60, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic burger with an added slice of cheese.', image: '/images/menu/item-106.jpg' },
  { id: 107, name: 'Sweet Corn Soup', price: 79, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A creamy and comforting soup made with sweet corn.', image: '/images/menu/item-107.jpg' },
  { id: 108, name: 'Delight Burger', price: 80, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A special burger with extra toppings for a delightful experience.', image: '/images/menu/item-108.jpg' },
  { id: 109, name: 'Manchow Soup', price: 89, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A popular Indo-Chinese soup with a spicy and sour flavor.', image: '/images/menu/item-109.jpg' },
  { id: 110, name: 'Hot N Sour Soup', price: 89, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic Chinese soup that is both spicy and sour.', image: '/images/menu/item-110.jpg' },
  { id: 111, name: 'Masala Sandwich', price: 90, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A toasted sandwich with a flavorful spiced potato filling.', image: '/images/menu/item-111.jpg' },
  { id: 112, name: 'Double Tikki Burger', price: 99, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A hearty burger with two vegetable patties.', image: '/images/menu/item-112.jpg' },
  { id: 113, name: 'Veg. Grill Sandwich', price: 110, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich with a delicious vegetable filling.', image: '/images/menu/item-113.jpg' },
  { id: 114, name: 'Veg. Cheese Grill Sandwich', price: 130, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich with vegetables and a layer of cheese.', image: '/images/menu/item-114.jpg' },
  { id: 115, name: 'Paneer Tikka Sandwich', price: 140, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich filled with spicy tandoori paneer tikka.', image: '/images/menu/item-115.jpg' },
  { id: 116, name: 'Cheese Grill Sandwich', price: 140, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic grilled cheese sandwich, gooey and comforting.', image: '/images/menu/item-116.jpg' },

  // Rice Bowl & Thali
  { id: 117, name: 'Tarkari Anna Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A flavorful rice dish cooked with mixed vegetables and spices.', image: '/images/menu/item-117.jpg' },
  { id: 118, name: 'Tamarind Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A tangy and spicy rice dish flavored with tamarind.', image: '/images/menu/item-118.jpg' },
  { id: 119, name: 'Sambhar Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A comforting mix of rice and lentil-based vegetable stew.', image: '/images/menu/item-119.jpg' },
  { id: 120, name: 'Rasam Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A light and flavorful dish of rice mixed with a tangy soup.', image: '/images/menu/item-120.jpg' },
  { id: 121, name: 'Lemon Rice', price: 159, category: 'Rice Bowl & Thali', description: 'A refreshing rice dish with a zesty lemon flavor.', image: '/images/menu/item-121.jpg' },
  { id: 122, name: 'Curd Rice', price: 159, category: 'Rice Bowl & Thali', description: 'A soothing and creamy dish of rice mixed with yogurt.', image: '/images/menu/item-122.jpg' },
  { id: 123, name: 'Tomato Rice', price: 169, category: 'Rice Bowl & Thali', description: 'A tangy and flavorful rice dish cooked with tomatoes and spices.', image: '/images/menu/item-123.jpg' },
  { id: 124, name: 'Coconut Rice', price: 169, category: 'Rice Bowl & Thali', description: 'A fragrant and delicious rice dish flavored with fresh coconut.', image: '/images/menu/item-124.jpg' },
  { id: 125, name: 'Student Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A budget-friendly and wholesome meal platter for students.', image: '/images/menu/item-125.jpg' },
  { id: 126, name: 'Anna Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A traditional South Indian meal platter with a variety of dishes.', image: '/images/menu/item-126.jpg' },
  { id: 127, name: 'Thala-Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A special and grand meal platter with a wide assortment of delicacies.', image: '/images/menu/item-127.jpg' },
  { id: 128, name: 'North Indian Thali', price: 299, category: 'Rice Bowl & Thali', description: 'A complete meal platter with popular North Indian dishes.', image: '/images/menu/item-128.jpg' },
  { id: 129, name: 'Sapad Thali', price: 299, category: 'Rice Bowl & Thali', description: 'An authentic and elaborate South Indian feast on a platter.', image: '/images/menu/item-129.jpg' },
  { id: 130, name: 'Chitranam Platter', price: 299, category: 'Rice Bowl & Thali', description: 'A platter with an assortment of flavored rice dishes.', image: '/images/menu/item-130.jpg' },

  // Main Course & Breads
  { id: 131, name: 'Puri', price: 15, category: 'Main Course & Breads', description: 'A single piece of fluffy, deep-fried Indian bread.', image: '/images/menu/item-131.jpg' },
  { id: 132, name: 'Tawa Roti', price: 15, category: 'Main Course & Breads', description: 'A classic Indian flatbread cooked on a griddle.', image: '/images/menu/item-132.jpg' },
  { id: 133, name: 'Tawa Butter Roti', price: 18, category: 'Main Course & Breads', description: 'A soft roti generously brushed with butter.', image: '/images/menu/item-133.jpg' },
  { id: 134, name: 'Dal Fry', price: 150, category: 'Main Course & Breads', description: 'A flavorful and comforting lentil curry.', image: '/images/menu/item-134.jpg' },
  { id: 135, name: 'Aloo Jeera', price: 160, category: 'Main Course & Breads', description: 'A simple yet delicious dish of potatoes flavored with cumin seeds.', image: '/images/menu/item-135.jpg' },
  { id: 136, name: 'Chana Masala', price: 160, category: 'Main Course & Breads', description: 'A popular North Indian dish of chickpeas in a spicy gravy.', image: '/images/menu/item-136.jpg' },
  { id: 137, name: 'Dal Tadka', price: 180, category: 'Main Course & Breads', description: 'A lentil curry tempered with aromatic spices.', image: '/images/menu/item-137.jpg' },
  { id: 138, name: 'Sev Tamatar', price: 180, category: 'Main Course & Breads', description: 'A tangy and spicy tomato curry topped with crispy sev.', image: '/images/menu/item-138.jpg' },
  { id: 139, name: 'Mix Veg.', price: 180, category: 'Main Course & Breads', description: 'A wholesome and flavorful curry with a mix of fresh vegetables.', image: '/images/menu/item-139.jpg' },
  { id: 140, name: 'Shahi Paneer', price: 190, category: 'Main Course & Breads', description: 'A rich and creamy curry with paneer in a tomato-based gravy.', image: '/images/menu/item-140.jpg' },
  { id: 141, name: 'Palak Paneer', price: 190, category: 'Main Course & Breads', description: 'A popular vegetarian dish with paneer in a creamy spinach gravy.', image: '/images/menu/item-141.jpg' },
  { id: 142, name: 'Matar Paneer', price: 190, category: 'Main Course & Breads', description: 'A delicious curry with paneer and green peas in a tomato-based sauce.', image: '/images/menu/item-142.jpg' },
  { id: 143, name: 'Paneer Butter Masala', price: 200, category: 'Main Course & Breads', description: 'A rich and creamy dish with paneer in a buttery tomato gravy.', image: '/images/menu/item-143.jpg' },
  { id: 144, name: 'Kadhai Paneer', price: 200, category: 'Main Course & Breads', description: 'A spicy and flavorful dish with paneer and bell peppers.', image: '/images/menu/item-144.jpg' },
  { id: 145, name: 'Paneer Bhurji', price: 220, category: 'Main Course & Breads', description: 'A savory dish of scrambled paneer with onions, tomatoes, and spices.', image: '/images/menu/item-145.jpg' },
  { id: 146, name: 'Missi Roti', price: 40, category: 'Main Course & Breads', description: 'A flavorful and savory flatbread made from gram flour and spices.', image: '/images/menu/item-146.jpg' },

  // Desserts, Curd & Beverages
  { id: 147, name: 'Boondi Raita', price: 29, category: 'Desserts, Curd & Beverages', description: 'A refreshing yogurt dip with small, crispy chickpea flour balls.', image: '/images/menu/item-147.jpg' },
  { id: 148, name: 'Veg. Raita', price: 39, category: 'Desserts, Curd & Beverages', description: 'A cooling yogurt dip with a mix of fresh vegetables.', image: '/images/menu/item-148.jpg' },
  { id: 149, name: 'Masala Chai', price: 39, category: 'Desserts, Curd & Beverages', description: 'A flavorful and aromatic Indian tea with a blend of spices.', image: '/images/menu/item-149.jpg' },
  { id: 150, name: 'Aam Panna', price: 49, category: 'Desserts, Curd & Beverages', description: 'A refreshing summer drink made from raw mangoes.', image: '/images/menu/item-150.jpg' },
  { id: 151, name: 'Fresh Lime Soda', price: 49, category: 'Desserts, Curd & Beverages', description: 'A zesty and refreshing drink made with fresh lime juice and soda.', image: '/images/menu/item-151.jpg' },
  { id: 152, name: 'Cold Coffee', price: 59, category: 'Desserts, Curd & Beverages', description: 'A classic and refreshing chilled coffee drink.', image: '/images/menu/item-152.jpg' },
  { id: 153, name: 'Tadka Adrak Chach', price: 59, category: 'Desserts, Curd & Beverages', description: 'A spiced buttermilk with a tempering of ginger and other spices.', image: '/images/menu/item-153.jpg' },
  { id: 154, name: 'Filter Coffee', price: 69, category: 'Desserts, Curd & Beverages', description: 'A strong and aromatic South Indian style coffee.', image: '/images/menu/item-154.jpg' },
  { id: 155, name: 'Coconut Water', price: 69, category: 'Desserts, Curd & Beverages', description: 'A natural and refreshing drink straight from the coconut.', image: '/images/menu/item-155.jpg' },
  { id: 156, name: 'Masala Coke', price: 69, category: 'Desserts, Curd & Beverages', description: 'A popular drink with a mix of cola and Indian spices.', image: '/images/menu/item-156.jpg' },
  { id: 157, name: 'Seasonal Juices', price: 69, category: 'Desserts, Curd & Beverages', description: 'Freshly squeezed juices from seasonal fruits.', image: '/images/menu/item-157.jpg' },
  { id: 158, name: 'Watermelon Mojito', price: 89, category: 'Desserts, Curd & Beverages', description: 'A refreshing and non-alcoholic mojito with fresh watermelon.', image: '/images/menu/item-158.jpg' },
  { id: 159, name: 'Blue Lagoon', price: 89, category: 'Desserts, Curd & Beverages', description: 'A vibrant and refreshing blue-colored mocktail.', image: '/images/menu/item-159.jpg' },
  { id: 160, name: 'Lassi', price: 99, category: 'Desserts, Curd & Beverages', description: 'A traditional yogurt-based drink, sweet and refreshing.', image: '/images/menu/item-160.jpg' },
  { id: 161, name: 'Virgin Mojito', price: 99, category: 'Desserts, Curd & Beverages', description: 'A classic non-alcoholic mojito with mint and lime.', image: '/images/menu/item-161.jpg' },
  { id: 162, name: 'Vanilla Shake', price: 99, category: 'Desserts, Curd & Beverages', description: 'A classic and creamy vanilla milkshake.', image: '/images/menu/item-162.jpg' },
  { id: 163, name: 'Pina Colada', price: 99, category: 'Desserts, Curd & Beverages', description: 'A tropical and creamy drink with pineapple and coconut flavors.', image: '/images/menu/item-163.jpg' },
  { id: 164, name: 'Payasam with Vermicelli', price: 109, category: 'Desserts, Curd & Beverages', description: 'A traditional South Indian pudding made with vermicelli and milk.', image: '/images/menu/item-164.jpg' },
  { id: 165, name: 'Pineapple Sheera', price: 129, category: 'Desserts, Curd & Beverages', description: 'A sweet and delicious semolina pudding with pineapple.', image: '/images/menu/item-165.jpg' },
  { id: 166, name: 'Strawberry Shake', price: 129, category: 'Desserts, Curd & Beverages', description: 'A refreshing milkshake made with fresh strawberries.', image: '/images/menu/item-166.jpg' },
  { id: 167, name: 'Banana Shake', price: 129, category: 'Desserts, Curd & Beverages', description: 'A healthy and creamy milkshake made with ripe bananas.', image: '/images/menu/item-167.jpg' },
  { id: 168, name: 'Kesari Bhaat', price: 139, category: 'Desserts, Curd & Beverages', description: 'A sweet and aromatic semolina dessert flavored with saffron.', image: '/images/menu/item-168.jpg' },
  { id: 169, name: 'Chocolate Shake', price: 139, category: 'Desserts, Curd & Beverages', description: 'A rich and indulgent chocolate milkshake.', image: '/images/menu/item-169.jpg' },
  { id: 170, name: 'Coconut Kesari Bhaat', price: 149, category: 'Desserts, Curd & Beverages', description: 'A flavorful variation of Kesari Bhaat with added coconut.', image: '/images/menu/item-170.jpg' },
  { id: 171, name: 'Oreo Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A delicious milkshake made with crushed Oreo cookies.', image: '/images/menu/item-171.jpg' },
  { id: 172, name: 'Badam Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A rich and creamy milkshake flavored with almonds.', image: '/images/menu/item-172.jpg' },
  { id: 173, name: 'Paan Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A unique and refreshing milkshake with the flavor of betel leaves.', image: '/images/menu/item-173.jpg' },
  { id: 174, name: 'Kitkat Shake', price: 169, category: 'Desserts, Curd & Beverages', description: 'A crunchy and delicious milkshake made with Kitkat chocolate bars.', image: '/images/menu/item-174.jpg' },
  { id: 175, name: 'Mineral Water', price: 20, category: 'Desserts, Curd & Beverages', description: 'Chilled mineral water bottle. Price is as per MRP.', image: '/images/menu/item-175.jpg' },

  // Extras & Party Menu
  { id: 176, name: 'Podi Masala', price: 10, category: 'Extras & Party Menu', description: 'A flavorful spice powder to enhance your meal.', image: '/images/menu/item-176.jpg' },
  { id: 177, name: 'Packing Charge', price: 20, category: 'Extras & Party Menu', description: 'Standard charge for all takeaway orders.', image: '/images/menu/item-177.jpg' },
  { id: 178, name: 'Puri (2pcs)', price: 29, category: 'Extras & Party Menu', description: 'Two pieces of fluffy deep-fried bread.', image: '/images/menu/item-178.jpg' },
  { id: 179, name: 'Aloo Bhaji', price: 29, category: 'Extras & Party Menu', description: 'A simple and delicious potato curry side dish.', image: '/images/menu/item-179.jpg' },
  { id: 180, name: 'Thairu (Curd)', price: 29, category: 'Extras & Party Menu', description: 'A side of plain, refreshing yogurt.', image: '/images/menu/item-180.jpg' },
  { id: 181, name: 'Cheese/Butter/Ghee', price: 30, category: 'Extras & Party Menu', description: 'An extra serving of cheese, butter, or ghee.', image: '/images/menu/item-181.jpg' },
  { id: 182, name: 'Unlimited Party Menu (₹299 Plan)', price: 299, category: 'Extras & Party Menu', description: 'Our basic unlimited party package per person. Please inquire for details.', image: '/images/menu/item-182.jpg' },
  { id: 183, name: 'Unlimited Party Menu (₹349 Plan)', price: 349, category: 'Extras & Party Menu', description: 'Our standard unlimited party package per person. Please inquire for details.', image: '/images/menu/item-183.jpg' },
  { id: 184, name: 'Unlimited Party Menu (₹399 Plan)', price: 399, category: 'Extras & Party Menu', description: 'Our premium unlimited party package per person. Please inquire for details.', image: '/images/menu/item-184.jpg' },
];


export const GALLERY_IMAGES: string[] = [
  '/images/gallery/gallery-1.jpg',
  '/images/gallery/gallery-2.jpg',
  '/images/gallery/gallery-3.jpg',
  '/images/gallery/gallery-4.jpg',
  '/images/gallery/gallery-5.jpg',
  '/images/gallery/gallery-6.jpg',
];

export const REVIEWS: Review[] = [
  {
    id: 1,
    author: 'Anjali Sharma',
    quote: 'The most authentic South Indian food I have had outside of Chennai! The dosas are perfectly crisp.',
    rating: 5,
    image: '/images/reviews/reviewer-1.jpg',
  },
  {
    id: 2,
    author: 'Rohan Mehta',
    quote: 'A wonderful dining experience. The ambiance is elegant and the service is top-notch. Highly recommend the filter coffee.',
    rating: 5,
    image: '/images/reviews/reviewer-2.jpg',
  },
  {
    id: 3,
    author: 'Priya Patel',
    quote: 'Srivalli is a gem in Jaipur. The food is fresh, flavorful, and beautifully presented. A must-visit for food lovers.',
    rating: 4,
    image: '/images/reviews/reviewer-3.jpg',
  },
];

export const HERO_IMAGE = '/images/hero/hero-main.jpg';
export const ABOUT_IMAGE = '/images/hero/about.jpg';