
import type { MenuItem, Review, NavLink } from './types';

export const NAV_LINKS: NavLink[] = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'menu', label: 'Menu' },
  { id: 'gallery', label: 'Gallery' },
  { id: 'contact', label: 'Contact' },
];

export const MENU_ITEMS: MenuItem[] = [
  // Dosa (SLOT 1)
  { id: 1, name: 'Plain Dosa', price: 119, category: 'Dosa', description: 'A classic crispy and savory crepe made from fermented rice and lentil batter.', image: '/images/menu/SLOT-1/PLAIN-DOSA (2).png' },
  { id: 2, name: 'Masala Dosa', price: 139, category: 'Dosa', description: 'A crispy dosa stuffed with a flavorful spiced potato filling.', image: '/images/menu/SLOT-1/masala-dosa.png' },
  { id: 3, name: 'Beetroot Dosa', price: 159, category: 'Dosa', description: 'A vibrant and healthy dosa with the wholesome goodness of beetroot.', image: '/images/menu/SLOT-1/beetroot-dosa.png' },
  { id: 4, name: 'Mysore Plain Dosa', price: 159, category: 'Dosa', description: 'A classic dosa layered with a spicy red chutney for an extra kick.', image: '/images/menu/SLOT-1/RAWA-MYSORE-PLAIN-DOSA.png' },
  { id: 5, name: 'Onion Masala Dosa', price: 159, category: 'Dosa', description: 'A delicious variation with sauteed onions and a savory potato masala.', image: '/images/menu/SLOT-1/ONION-MASALA-DOSA.png' },
  { id: 6, name: 'Mysore Masala Dosa', price: 169, category: 'Dosa', description: 'Features a spicy chutney spread and a savory potato filling.', image: '/images/menu/SLOT-1/mysore-masala-dosa.png' },
  { id: 7, name: 'Butter Masala Dosa', price: 169, category: 'Dosa', description: 'A rich and indulgent dosa cooked with a generous amount of butter.', image: '/images/menu/SLOT-1/BUTTER-MASALA-DOSA.png' },
  { id: 8, name: 'Ghee Roast Plain Dosa', price: 169, category: 'Dosa', description: 'A plain dosa roasted to perfection with aromatic clarified butter (ghee).', image: '/images/menu/SLOT-1/ghee-roast-dosa.png' },
  { id: 9, name: 'Podi Masala Dosa', price: 169, category: 'Dosa', description: 'Dosa coated with a flavorful and aromatic spiced powder (podi).', image: '/images/menu/SLOT-1/PODI-MASALA-DOSA.png' },
  { id: 10, name: 'Rawa Mysore Plain Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa with a layer of spicy Mysore chutney.', image: '/images/menu/SLOT-1/RAWA-MYSORE-PLAIN-DOSA.png' },
  { id: 11, name: 'Rawa Ghee Roast Plain Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa roasted with fragrant ghee.', image: '/images/menu/SLOT-1/RAWA-GHEE-ROAST-PLAIN-DOSA.png' },
  { id: 12, name: 'Rawa Masala Dosa', price: 169, category: 'Dosa', description: 'A crispy semolina dosa with a spiced potato filling.', image: '/images/menu/SLOT-1/RAWA-MASALA-DOSA.png' },
  { id: 13, name: 'Cheese Masala Dosa', price: 179, category: 'Dosa', description: 'A cheesy twist on the classic masala dosa, loved by all ages.', image: '/images/menu/SLOT-1/CHEESE-MASALA-D0SA.png' },
  { id: 14, name: 'Ghee Roast Masala Dosa', price: 179, category: 'Dosa', description: 'A masala dosa roasted with ghee for a rich, aromatic flavor.', image: '/images/menu/SLOT-1/GHEE-ROAST-MASALA-DOSA.png' },
  { id: 15, name: 'Rawa Mysore Masala Dosa', price: 179, category: 'Dosa', description: 'Crispy semolina dosa with spicy chutney and potato filling.', image: '/images/menu/SLOT-1/RAWA-MYSORE-MASALA-DOSA.png' },
  { id: 16, name: 'Rawa Onion Masala Dosa', price: 179, category: 'Dosa', description: 'Semolina dosa with onions and a spiced potato filling.', image: '/images/menu/SLOT-1/RAWA-ONION-MASALA-DOSA.png' },
  { id: 17, name: 'Rawa Paneer Masala Dosa', price: 179, category: 'Dosa', description: 'A semolina dosa filled with spiced cottage cheese (paneer).', image: '/images/menu/SLOT-1/RAWA-PANEER-MASALA-DOSA.png' },
  { id: 18, name: 'Rawa Ghee Roast Masala Dosa', price: 179, category: 'Dosa', description: 'Crispy semolina dosa with potato filling, roasted in ghee.', image: '/images/menu/SLOT-1/RAWA-GHEE-ROAST-MASALA-DOSA.png' },
  { id: 19, name: 'Paneer Masala Dosa', price: 189, category: 'Dosa', description: 'A classic dosa with a delicious spiced paneer filling.', image: '/images/menu/SLOT-1/PANEER-MASALA-DOSA.png' },
  { id: 20, name: 'Paper Masala Dosa', price: 249, category: 'Dosa', description: 'An extra-large, paper-thin and crispy dosa with a side of masala.', image: '/images/menu/SLOT-1/masala-dosa.png' },
  { id: 21, name: 'Mini Dosa Platter', price: 299, category: 'Dosa', description: 'An assortment of our popular mini dosas, perfect for trying a bit of everything.', image: '/images/menu/SLOT-1/MINI-DOSA-PLATTER.png' },
  
  // Srivalli Special Dosa (SLOT 2)
  { id: 22, name: 'Patta Dosa', price: 189, category: 'Srivalli Special Dosa', description: 'A unique and flavorful dosa shaped like a leaf, a true specialty.', image: '/images/menu/SLOT-2/patta-dosa.png' },
  { id: 23, name: 'Palak Paneer Dosa', price: 189, category: 'Srivalli Special Dosa', description: 'A healthy and delicious dosa with a creamy spinach and paneer filling.', image: '/images/menu/SLOT-2/PALAK-PANEER-DOSA.png' },
  { id: 24, name: 'Peri-Peri Cheese Dosa', price: 219, category: 'Srivalli Special Dosa', description: 'A spicy and cheesy fusion dosa for the adventurous palate.', image: '/images/menu/SLOT-2/PERI-PERI-CHEESE-DOSA.png' },
  { id: 25, name: 'Paneer Cheese Surma', price: 219, category: 'Srivalli Special Dosa', description: 'A rich and savory dosa with a blend of paneer and cheese.', image: '/images/menu/SLOT-2/PANEER-CHEESE-SURMA.png' },
  { id: 26, name: 'Paneer Tikka Dosa', price: 219, category: 'Srivalli Special Dosa', description: 'A dosa filled with smoky and spicy tandoori paneer tikka.', image: '/images/menu/SLOT-2/PANEER-TIKKA-DOSA.png' },
  { id: 27, name: 'Cheese Burst Dosa', price: 229, category: 'Srivalli Special Dosa', description: 'An indulgent dosa loaded with molten, gooey cheese.', image: '/images/menu/SLOT-2/cheese-burst-dosa.png' },
  { id: 28, name: 'Cheese Corn Dosa', price: 229, category: 'Srivalli Special Dosa', description: 'A delightful combination of sweet corn and savory cheese in a crispy dosa.', image: '/images/menu/SLOT-2/CHEESE-CORN-DOSA.png' },
  { id: 29, name: 'Pizza Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'An exciting fusion of Italian pizza toppings on a South Indian dosa base.', image: '/images/menu/SLOT-2/PIZZA-DOSA (2).png' },
  { id: 30, name: 'Jinni Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A popular Mumbai-style dosa loaded with vegetables and cheese.', image: '/images/menu/SLOT-2/JINNI-DOSA.png' },
  { id: 31, name: 'Dilkhoosh Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A special sweet and savory dosa that is sure to delight your taste buds.', image: '/images/menu/SLOT-2/DILKHOOSH-DOSA.png' },
  { id: 32, name: 'Pasta Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A creative fusion dish combining Italian pasta and a South Indian dosa.', image: '/images/menu/SLOT-2/PASTA-DOSA (2).png' },
  { id: 33, name: 'Manchurian Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'An Indo-Chinese delight with a tangy Manchurian filling in a crispy dosa.', image: '/images/menu/SLOT-2/MANCHURIAN-DOSA.png' },
  { id: 34, name: 'Noodles Dosa', price: 239, category: 'Srivalli Special Dosa', description: 'A unique dosa filled with flavorful stir-fried noodles.', image: '/images/menu/SLOT-2/NOODLES-DOSA.png' },
  { id: 35, name: 'Srivalli Family Dosa', price: 349, category: 'Srivalli Special Dosa', description: 'A giant, shareable dosa perfect for families and groups.', image: '/images/menu/SLOT-2/SRIVALLI-FAMILY-DOSA.png' },

  // Uttapam & Upma (SLOT 3)
  { id: 36, name: 'Plain Uttapam', price: 149, category: 'Uttapam & Upma', description: 'A thick, savory pancake made from rice batter, soft and fluffy.', image: '/images/menu/slot-3/plain-uttapam.png' },
  { id: 37, name: 'Onion Uttapam', price: 159, category: 'Uttapam & Upma', description: 'A savory uttapam topped with finely chopped, flavorful onions.', image: '/images/menu/slot-3/onion-uttapam.png' },
  { id: 38, name: 'Coconut Uttapam', price: 169, category: 'Uttapam & Upma', description: 'A delicious uttapam topped with fresh, grated coconut.', image: '/images/menu/slot-3/coconut-uttapam.png' },
  { id: 39, name: 'Onion Tomato Uttapam', price: 169, category: 'Uttapam & Upma', description: 'A classic combination of onions and tomatoes on a soft uttapam.', image: '/images/menu/slot-3/onion-tomato-uttapam.png' },
  { id: 40, name: 'Mixed Veg Uttapam', price: 179, category: 'Uttapam & Upma', description: 'A wholesome uttapam loaded with a variety of fresh vegetables.', image: '/images/menu/slot-3/mixed-veg-uttapam.png' },
  { id: 41, name: 'Paneer Tikka Uttapam', price: 189, category: 'Uttapam & Upma', description: 'A fusion uttapam topped with spicy and smoky paneer tikka.', image: '/images/menu/slot-3/paneer-tikka-uttapam.png' },
  { id: 42, name: 'Mini Uttapam Platter', price: 299, category: 'Uttapam & Upma', description: 'An assortment of our popular mini uttapams.', image: '/images/menu/slot-3/Mini Uttapam Platter (Plain, Podi, Tomato).png' },
  { id: 43, name: 'Vegetable Upma', price: 129, category: 'Uttapam & Upma', description: 'A savory porridge made from semolina and mixed vegetables.', image: '/images/menu/slot-3/vegetable-upma.png' },
  { id: 44, name: 'Paneer vegetable Upma', price: 159, category: 'Uttapam & Upma', description: 'A protein-rich upma with added cottage cheese and vegetables.', image: '/images/menu/slot-3/paneer-vegetable-upma.png' },

  // Idli & Srivalli Special Dishes (SLOT 4)
  { id: 45, name: 'Steam Idli', price: 79, category: 'Idli & Srivalli Special Dishes', description: 'Soft, fluffy steamed rice cakes, a South Indian staple.', image: '/images/menu/slot-4/steam-idli.png' },
  { id: 46, name: 'Mini Idli', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Bite-sized idlis, perfect for a light snack or appetizer.', image: '/images/menu/slot-4/mini-idli (2).png' },
  { id: 47, name: 'Medu Vada', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and savory deep-fried lentil doughnuts.', image: '/images/menu/slot-4/medu-vada.png' },
  { id: 48, name: 'Idli Chaat', price: 99, category: 'Idli & Srivalli Special Dishes', description: 'A tangy and spicy snack made with idli, chutneys, and yogurt.', image: '/images/menu/slot-4/idli-chaat.png' },
  { id: 49, name: 'White Sauce Idli', price: 119, category: 'Idli & Srivalli Special Dishes', description: 'A fusion dish with idlis tossed in a creamy white sauce.', image: '/images/menu/slot-4/white-sauce-idli.png' },
  { id: 50, name: 'Sejwan Idli', price: 129, category: 'Idli & Srivalli Special Dishes', description: 'Spicy idlis tossed in a fiery Schezwan sauce.', image: '/images/menu/slot-4/sejwan-idli.png' },
  { id: 51, name: 'Chinese Idli', price: 149, category: 'Idli & Srivalli Special Dishes', description: 'An Indo-Chinese style dish with crispy fried idlis.', image: '/images/menu/slot-4/chinese-idli.png' },
  { id: 52, name: 'Puri Bhaaji', price: 79, category: 'Idli & Srivalli Special Dishes', description: 'Fluffy deep-fried bread served with a savory potato curry.', image: '/images/menu/slot-4/puri-bhaaji.png' },
  { id: 53, name: 'Appey', price: 79, category: 'Idli & Srivalli Special Dishes', description: 'Small, round, savory pancakes that are crispy on the outside and soft inside.', image: '/images/menu/slot-4/appey.png' },
  { id: 54, name: 'Idli pakoda', price: 89, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and delicious deep-fried idli fritters.', image: '/images/menu/slot-4/idli-pakoda.png' },
  { id: 55, name: 'Thaate Idli', price: 99, category: 'Idli & Srivalli Special Dishes', description: 'A large, plate-sized idli that is exceptionally soft and fluffy.', image: '/images/menu/slot-4/thaate-idli.png' },
  { id: 56, name: 'Ghee Podi Idli', price: 109, category: 'Idli & Srivalli Special Dishes', description: 'Mini idlis tossed in fragrant ghee and aromatic spiced powder.', image: '/images/menu/slot-4/ghee-podi-idli.png' },
  { id: 57, name: 'Dal Vada', price: 109, category: 'Idli & Srivalli Special Dishes', description: 'Crispy and savory deep-fried lentil fritters.', image: '/images/menu/slot-4/daal-vada.png' },
  { id: 58, name: 'Potato Bonda with Chutney', price: 119, category: 'Idli & Srivalli Special Dishes', description: 'Spiced potato balls coated in batter and deep-fried to perfection.', image: '/images/menu/slot-4/Potato Bonda with Chutney.png' },
  { id: 59, name: 'Rasam Papadam', price: 129, category: 'Idli & Srivalli Special Dishes', description: 'A tangy and spicy South Indian soup served with crispy papad.', image: '/images/menu/slot-4/rassam-pappadum.png' },
  { id: 60, name: 'Fried Idli', price: 149, category: 'Idli & Srivalli Special Dishes', description: 'Crispy fried idli cubes tossed with spices.', image: '/images/menu/slot-4/fried-idli.png' },
  
  // Agra Chat & Pizza (SLOT 5)
  { id: 61, name: 'Pani Puri', price: 19, category: 'Agra Chat & Pizza', description: 'Hollow crispy balls filled with a tangy and spicy mint water.', image: '/images/menu/slot-5/pani-puri.png' },
  { id: 62, name: 'Sev Puri', price: 39, category: 'Agra Chat & Pizza', description: 'Flat crispy discs topped with potatoes, chutneys, and crunchy sev.', image: '/images/menu/slot-5/sev-puri.png' },
  { id: 63, name: 'Aloo Chat', price: 49, category: 'Agra Chat & Pizza', description: 'A tangy and spicy snack made with fried potatoes and chutneys.', image: '/images/menu/slot-5/aloo-chat.png' },
  { id: 64, name: 'Masala Papad', price: 49, category: 'Agra Chat & Pizza', description: 'A crispy papad topped with onions, tomatoes, and spices.', image: '/images/menu/slot-5/masala-papad.png' },
  { id: 65, name: 'Dahi Vada', price: 49, category: 'Agra Chat & Pizza', description: 'Soft lentil dumplings soaked in creamy yogurt and topped with chutneys.', image: '/images/menu/slot-5/dahi-vada.png' },
  { id: 66, name: 'Wada Pav', price: 49, category: 'Agra Chat & Pizza', description: 'Mumbai\'s iconic street food, a spiced potato fritter in a soft bun.', image: '/images/menu/slot-5/vada-pav.png' },
  { id: 67, name: 'Mumbai Bhel Puri', price: 59, category: 'Agra Chat & Pizza', description: 'A savory snack made with puffed rice, vegetables, and tangy tamarind sauce.', image: '/images/menu/slot-5/mumbai-bhel-puri.png' },
  { id: 68, name: 'Papri Chat', price: 69, category: 'Agra Chat & Pizza', description: 'A popular street food snack with crispy wafers, potatoes, and chutneys.', image: '/images/menu/slot-5/papri-chaat.png' },
  { id: 69, name: 'Fruit Chat', price: 69, category: 'Agra Chat & Pizza', description: 'A refreshing and healthy snack made with a mix of fresh fruits and spices.', image: '/images/menu/slot-5/fruit-chaat.png' },
  { id: 70, name: 'Chana Chat', price: 79, category: 'Agra Chat & Pizza', description: 'A protein-packed and flavorful salad made with chickpeas.', image: '/images/menu/slot-5/chana-chaat.png' },
  { id: 71, name: 'Pav Bhaji', price: 89, category: 'Agra Chat & Pizza', description: 'A hearty dish of mashed vegetable curry served with soft, buttery buns.', image: '/images/menu/slot-5/pav-bhaji.png' },
  { id: 72, name: 'Aloo Tiki', price: 99, category: 'Agra Chat & Pizza', description: 'Spiced potato patties, shallow-fried until golden and crisp.', image: '/images/menu/slot-5/Aloo-Tiki-(Kela-Saboo-Dana.png' },
  { id: 73, name: 'Paneer Chilla', price: 99, category: 'Agra Chat & Pizza', description: 'A savory pancake made from gram flour, filled with spiced paneer.', image: '/images/menu/slot-5/paneer-chilla.png' },
  { id: 74, name: 'Dry Fruit Chat', price: 99, category: 'Agra Chat & Pizza', description: 'A rich and healthy chaat made with a mix of dry fruits and nuts.', image: '/images/menu/slot-5/dry-fruit-chaat.png' },
  { id: 75, name: 'Chole Bhature', price: 109, category: 'Agra Chat & Pizza', description: 'A classic North Indian dish of fluffy fried bread with a spicy chickpea curry.', image: '/images/menu/slot-5/chole-bhature.png' },
  { id: 76, name: 'Onion Pizza', price: 139, category: 'Agra Chat & Pizza', description: 'A simple yet delicious pizza topped with fresh onions and cheese.', image: '/images/menu/slot-5/onion-pizza.png' },
  { id: 77, name: 'Corn Pizza', price: 159, category: 'Agra Chat & Pizza', description: 'A tasty pizza topped with sweet corn and mozzarella cheese.', image: '/images/menu/slot-5/corn-pizza.png' },
  { id: 78, name: 'OTC Pizza', price: 169, category: 'Agra Chat & Pizza', description: 'A flavorful pizza with onion, tomato, and capsicum toppings.', image: '/images/menu/slot-5/otc-pizza.png' },
  { id: 79, name: 'Margherita Pizza', price: 169, category: 'Agra Chat & Pizza', description: 'A classic pizza with tomato sauce, mozzarella cheese, and fresh basil.', image: '/images/menu/slot-5/margherita-pizza.png' },
  { id: 80, name: 'Tandoori Paneer Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'An Indian-style pizza with marinated tandoori paneer.', image: '/images/menu/slot-5/tandoori-paneer-pizza.png' },
  { id: 81, name: 'Peppy Paneer Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'A spicy and flavorful pizza with paneer and zesty peppers.', image: '/images/menu/slot-5/peppy-paneer-pizza.png' },
  { id: 82, name: 'Farmhouse Pizza', price: 199, category: 'Agra Chat & Pizza', description: 'A wholesome pizza loaded with a variety of fresh farm vegetables.', image: '/images/menu/slot-5/farmhouse-pizza.png' },
  
  // Chinese (SLOT 6)
  { id: 83, name: 'Momos', price: 50, category: 'Chinese', description: 'Steamed dumplings filled with a savory vegetable stuffing.', image: '/images/menu/SLOT-6/momos.jpg' },
  { id: 84, name: 'Plain Maggi', price: 70, category: 'Chinese', description: 'A classic comfort food, instant noodles cooked to perfection.', image: '/images/menu/SLOT-6/plain-maggi.jpg' },
  { id: 85, name: 'Veg Spring Roll', price: 99, category: 'Chinese', description: 'Crispy fried rolls filled with a delicious vegetable stuffing.', image: '/images/menu/SLOT-6/veg-spring-roll.jpg' },
  { id: 86, name: 'Masala Maggi', price: 100, category: 'Chinese', description: 'Instant noodles cooked with a flavorful blend of Indian spices.', image: '/images/menu/SLOT-6/masala-maggi.jpg' },
  { id: 87, name: 'Chowmein Roll', price: 109, category: 'Chinese', description: 'A tasty roll stuffed with stir-fried noodles and vegetables.', image: '/images/menu/SLOT-6/chowmein-roll.jpg' },
  { id: 88, name: 'Fried Rice', price: 120, category: 'Chinese', description: 'A classic Indo-Chinese dish of stir-fried rice with vegetables.', image: '/images/menu/SLOT-6/fried-rice.jpg' },
  { id: 89, name: 'Veg Crispy', price: 129, category: 'Chinese', description: 'Crispy fried vegetables tossed in a tangy and spicy sauce.', image: '/images/menu/SLOT-6/veg-crispy.jpg' },
  { id: 90, name: 'Hakka Noodles', price: 130, category: 'Chinese', description: 'Stir-fried noodles with a mix of vegetables and savory sauces.', image: '/images/menu/SLOT-6/hakka-noodles.jpg' },
  { id: 91, name: 'Veg. Noodles', price: 130, category: 'Chinese', description: 'A simple yet delicious dish of stir-fried noodles with vegetables.', image: '/images/menu/SLOT-6/veg-noodles.jpg' },
  { id: 92, name: 'Manchurian Dry', price: 130, category: 'Chinese', description: 'Deep-fried vegetable balls tossed in a tangy and savory sauce.', image: '/images/menu/SLOT-6/manchurian-dry.jpg' },
  { id: 93, name: 'Manchurian Gravy', price: 130, category: 'Chinese', description: 'Vegetable balls in a flavorful and tangy gravy.', image: '/images/menu/SLOT-6/manchurian-gravy.jpg' },
  { id: 94, name: 'American Chopsy', price: 139, category: 'Chinese', description: 'A delightful dish of crispy noodles topped with a sweet and tangy vegetable sauce.', image: '/images/menu/SLOT-6/american-chopsy.jpg' },
  { id: 95, name: 'Chinese Bhel', price: 139, category: 'Chinese', description: 'A fusion snack made with crispy noodles, vegetables, and tangy sauces.', image: '/images/menu/SLOT-6/chinese-bhel.jpg' },
  { id: 96, name: 'Chilli Potato', price: 139, category: 'Chinese', description: 'Crispy fried potatoes tossed in a spicy and tangy chili sauce.', image: '/images/menu/SLOT-6/chilli-potato.jpg' },
  { id: 97, name: 'Chilli Paneer Dry', price: 150, category: 'Chinese', description: 'A popular Indo-Chinese dish of fried paneer tossed in a spicy sauce.', image: '/images/menu/SLOT-6/chilli-paneer-dry.jpg' },
  { id: 98, name: 'Chilli Paneer Gravy', price: 150, category: 'Chinese', description: 'Fried paneer in a flavorful and spicy gravy.', image: '/images/menu/SLOT-6/chilli-paneer-gravy.jpg' },
  { id: 99, name: 'Honey Chilli Potato', price: 159, category: 'Chinese', description: 'A sweet and spicy dish of crispy fried potatoes coated in honey chili sauce.', image: '/images/menu/SLOT-6/honey-chilli-potato.jpg' },
  { id: 100, name: 'Red Sauce Pasta', price: 179, category: 'Chinese', description: 'A classic Italian pasta dish in a tangy tomato-based sauce.', image: '/images/menu/SLOT-6/red-sauce-pasta.jpg' },
  { id: 101, name: 'White Sauce Pasta', price: 189, category: 'Chinese', description: 'A creamy and delicious pasta dish in a rich white sauce.', image: '/images/menu/SLOT-6/white-sauce-pasta.jpg' },
  { id: 102, name: 'French Fries', price: 100, category: 'Chinese', description: 'Classic crispy and golden deep-fried potato strips.', image: '/images/menu/SLOT-6/chilli-potato.jpg' },
  
  // Breakfast (Tea, Sandwich, Soup, Burger) (SLOT 7)
  { id: 103, name: 'Tea', price: 20, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A refreshing cup of hot tea to start your day.', image: '/images/menu/SLOT-7/tea.jpg' },
  { id: 104, name: 'Tomato Soup', price: 49, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic and comforting soup made with fresh tomatoes.', image: '/images/menu/SLOT-7/tomato-soup.jpg' },
  { id: 105, name: 'Classic Burger', price: 50, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A simple and delicious burger with a vegetable patty.', image: '/images/menu/SLOT-7/classic-burger.jpg' },
  { id: 106, name: 'Cheese Burger', price: 60, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic burger with an added slice of cheese.', image: '/images/menu/SLOT-7/cheese-burger.jpg' },
  { id: 107, name: 'Sweet Corn Soup', price: 79, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A creamy and comforting soup made with sweet corn.', image: '/images/menu/SLOT-7/sweet-corn-soup.jpg' },
  { id: 108, name: 'Delight Burger', price: 80, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A special burger with extra toppings for a delightful experience.', image: '/images/menu/SLOT-7/delight-burger.jpg' },
  { id: 109, name: 'Manchow Soup', price: 89, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A popular Indo-Chinese soup with a spicy and sour flavor.', image: '/images/menu/SLOT-7/manchow-soup.jpg' },
  { id: 110, name: 'Hot N Sour Soup', price: 89, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic Chinese soup that is both spicy and sour.', image: '/images/menu/SLOT-7/hot-n-sour-soup.jpg' },
  { id: 111, name: 'Masala Sandwich', price: 90, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A toasted sandwich with a flavorful spiced potato filling.', image: '/images/menu/SLOT-7/masala-sandwich.jpg' },
  { id: 112, name: 'Double Tikki Burger', price: 99, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A hearty burger with two vegetable patties.', image: '/images/menu/SLOT-7/double-tikki-burger.jpg' },
  { id: 113, name: 'Veg. Grill Sandwich', price: 110, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich with a delicious vegetable filling.', image: '/images/menu/SLOT-7/veg-grill-sandwich.jpg' },
  { id: 114, name: 'Veg. Cheese Grill Sandwich', price: 130, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich with vegetables and a layer of cheese.', image: '/images/menu/SLOT-7/veg-cheese-grill-sandwich.jpg' },
  { id: 115, name: 'Paneer Tikka Sandwich', price: 140, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A grilled sandwich filled with spicy tandoori paneer tikka.', image: '/images/menu/SLOT-7/paneer-tikka-sandwich.jpg' },
  { id: 116, name: 'Cheese Grill Sandwich', price: 140, category: 'Breakfast (Tea, Sandwich, Soup, Burger)', description: 'A classic grilled cheese sandwich, gooey and comforting.', image: '/images/menu/SLOT-7/cheese-grill-sandwich.jpg' },

  // Rice Bowl & Thali (SLOT 8)
  { id: 117, name: 'Tarkari Anna Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A flavorful rice dish cooked with mixed vegetables and spices.', image: '/images/menu/slot-8/tarkari-anna-rice.jpg' },
  { id: 118, name: 'Tamarind Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A tangy and spicy rice dish flavored with tamarind.', image: '/images/menu/slot-8/tamarind-rice.jpg' },
  { id: 119, name: 'Sambhar Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A comforting mix of rice and lentil-based vegetable stew.', image: '/images/menu/slot-8/sambhar-rice.jpg' },
  { id: 120, name: 'Rasam Rice', price: 149, category: 'Rice Bowl & Thali', description: 'A light and flavorful dish of rice mixed with a tangy soup.', image: '/images/menu/slot-8/rasam-rice.jpg' },
  { id: 121, name: 'Lemon Rice', price: 159, category: 'Rice Bowl & Thali', description: 'A refreshing rice dish with a zesty lemon flavor.', image: '/images/menu/slot-8/lemon-rice.jpg' },
  { id: 122, name: 'Curd Rice', price: 159, category: 'Rice Bowl & Thali', description: 'A soothing and creamy dish of rice mixed with yogurt.', image: '/images/menu/slot-8/curd-rice.jpg' },
  { id: 123, name: 'Tomato Rice', price: 169, category: 'Rice Bowl & Thali', description: 'A tangy and flavorful rice dish cooked with tomatoes and spices.', image: '/images/menu/slot-8/tomato-rice.jpg' },
  { id: 124, name: 'Coconut Rice', price: 169, category: 'Rice Bowl & Thali', description: 'A fragrant and delicious rice dish flavored with fresh coconut.', image: '/images/menu/slot-8/coconut-rice.jpg' },
  { id: 125, name: 'Student Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A budget-friendly and wholesome meal platter for students.', image: '/images/menu/slot-8/student-thali.jpg' },
  { id: 126, name: 'Anna Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A traditional South Indian meal platter with a variety of dishes.', image: '/images/menu/slot-8/anna-thali.jpg' },
  { id: 127, name: 'Thala-Thali', price: 249, category: 'Rice Bowl & Thali', description: 'A special and grand meal platter with a wide assortment of delicacies.', image: '/images/menu/slot-8/thala-thali.jpg' },
  { id: 128, name: 'North Indian Thali', price: 299, category: 'Rice Bowl & Thali', description: 'A complete meal platter with popular North Indian dishes.', image: '/images/menu/slot-8/north-indian-thali.jpg' },
  { id: 129, name: 'Sapad Thali', price: 299, category: 'Rice Bowl & Thali', description: 'An authentic and elaborate South Indian feast on a platter.', image: '/images/menu/slot-8/sapad-thali.jpg' },
  { id: 130, name: 'Chitranam Platter', price: 299, category: 'Rice Bowl & Thali', description: 'A platter with an assortment of flavored rice dishes.', image: '/images/menu/slot-8/chitranam-platter.jpg' },

  // Main Course & Breads (SLOT 9)
  { id: 131, name: 'Puri', price: 15, category: 'Main Course & Breads', description: 'A single piece of fluffy, deep-fried Indian bread.', image: '/images/menu/SLOT-9/puri.png' },
  { id: 132, name: 'Tawa Roti', price: 15, category: 'Main Course & Breads', description: 'A classic Indian flatbread cooked on a griddle.', image: '/images/menu/SLOT-9/tawa-roti.png' },
  { id: 133, name: 'Tawa Butter Roti', price: 18, category: 'Main Course & Breads', description: 'A soft roti generously brushed with butter.', image: '/images/menu/SLOT-9/tawa-butter-roti.png' },
  { id: 134, name: 'Dal Fry', price: 150, category: 'Main Course & Breads', description: 'A flavorful and comforting lentil curry.', image: '/images/menu/SLOT-9/dal-fry.png' },
  { id: 135, name: 'Aloo Jeera', price: 160, category: 'Main Course & Breads', description: 'A simple yet delicious dish of potatoes flavored with cumin seeds.', image: '/images/menu/SLOT-9/aloo-jeera.png' },
  { id: 136, name: 'Chana Masala', price: 160, category: 'Main Course & Breads', description: 'A popular North Indian dish of chickpeas in a spicy gravy.', image: '/images/menu/SLOT-9/chana-masala.png' },
  { id: 137, name: 'Dal Tadka', price: 180, category: 'Main Course & Breads', description: 'A lentil curry tempered with aromatic spices.', image: '/images/menu/SLOT-9/dal-tadka.png' },
  { id: 138, name: 'Sev Tamatar', price: 180, category: 'Main Course & Breads', description: 'A tangy and spicy tomato curry topped with crispy sev.', image: '/images/menu/SLOT-9/sev-tamatar.png' },
  { id: 139, name: 'Mix Veg.', price: 180, category: 'Main Course & Breads', description: 'A wholesome and flavorful curry with a mix of fresh vegetables.', image: '/images/menu/SLOT-9/mix-veg.png' },
  { id: 140, name: 'Shahi Paneer', price: 190, category: 'Main Course & Breads', description: 'A rich and creamy curry with paneer in a tomato-based gravy.', image: '/images/menu/SLOT-9/shahi-paneer.png' },
  { id: 141, name: 'Palak Paneer', price: 190, category: 'Main Course & Breads', description: 'A popular vegetarian dish with paneer in a creamy spinach gravy.', image: '/images/menu/SLOT-9/palak-paneer.png' },
  { id: 142, name: 'Matar Paneer', price: 190, category: 'Main Course & Breads', description: 'A delicious curry with paneer and green peas in a tomato-based sauce.', image: '/images/menu/SLOT-9/matar-paneer.png' },
  { id: 143, name: 'Paneer Butter Masala', price: 200, category: 'Main Course & Breads', description: 'A rich and creamy dish with paneer in a buttery tomato gravy.', image: '/images/menu/SLOT-9/paneer-butter-masala.png' },
  { id: 144, name: 'Kadhai Paneer', price: 200, category: 'Main Course & Breads', description: 'A spicy and flavorful dish with paneer and bell peppers.', image: '/images/menu/SLOT-9/kadhai-paneer.png' },
  { id: 145, name: 'Paneer Bhurji', price: 220, category: 'Main Course & Breads', description: 'A savory dish of scrambled paneer with onions, tomatoes, and spices.', image: '/images/menu/SLOT-9/paneer-bhurji.png' },
  { id: 146, name: 'Missi Roti', price: 40, category: 'Main Course & Breads', description: 'A flavorful and savory flatbread made from gram flour and spices.', image: '/images/menu/SLOT-9/tawa-roti.png' },

  // Desserts, Curd & Beverages (SLOT 10)
  { id: 147, name: 'Boondi Raita', price: 29, category: 'Desserts, Curd & Beverages', description: 'A refreshing yogurt dip with small, crispy chickpea flour balls.', image: '/images/menu/SLOT-10/boondi-raita.png' },
  { id: 148, name: 'Veg. Raita', price: 39, category: 'Desserts, Curd & Beverages', description: 'A cooling yogurt dip with a mix of fresh vegetables.', image: '/images/menu/SLOT-10/veg-raita.png' },
  { id: 149, name: 'Masala Chai', price: 39, category: 'Desserts, Curd & Beverages', description: 'A flavorful and aromatic Indian tea with a blend of spices.', image: '/images/menu/SLOT-10/masala-chai.png' },
  { id: 150, name: 'Aam Panna', price: 49, category: 'Desserts, Curd & Beverages', description: 'A refreshing summer drink made from raw mangoes.', image: '/images/menu/SLOT-10/aam-panna.png' },
  { id: 151, name: 'Fresh Lime Soda', price: 49, category: 'Desserts, Curd & Beverages', description: 'A zesty and refreshing drink made with fresh lime juice and soda.', image: '/images/menu/SLOT-10/fresh-lime-soda.png' },
  { id: 152, name: 'Cold Coffee', price: 59, category: 'Desserts, Curd & Beverages', description: 'A classic and refreshing chilled coffee drink.', image: '/images/menu/SLOT-10/cold-coffee.png' },
  { id: 153, name: 'Tadka Adrak Chach', price: 59, category: 'Desserts, Curd & Beverages', description: 'A spiced buttermilk with a tempering of ginger and other spices.', image: '/images/menu/SLOT-10/tadka-adrak-chai.png' },
  { id: 154, name: 'Filter Coffee', price: 69, category: 'Desserts, Curd & Beverages', description: 'A strong and aromatic South Indian style coffee.', image: '/images/menu/SLOT-10/filter-coffee.png' },
  { id: 155, name: 'Coconut Water', price: 69, category: 'Desserts, Curd & Beverages', description: 'A natural and refreshing drink straight from the coconut.', image: '/images/menu/SLOT-10/cocunut-water.png' },
  { id: 156, name: 'Masala Coke', price: 69, category: 'Desserts, Curd & Beverages', description: 'A popular drink with a mix of cola and Indian spices.', image: '/images/menu/SLOT-10/masala-coke.png' },
  { id: 157, name: 'Seasonal Juices', price: 69, category: 'Desserts, Curd & Beverages', description: 'Freshly squeezed juices from seasonal fruits.', image: '/images/menu/SLOT-10/seasonal-juice.png' },
  { id: 158, name: 'Watermelon Mojito', price: 89, category: 'Desserts, Curd & Beverages', description: 'A refreshing and non-alcoholic mojito with fresh watermelon.', image: '/images/menu/SLOT-10/watermelon-mohito.png' },
  { id: 159, name: 'Blue Lagoon', price: 89, category: 'Desserts, Curd & Beverages', description: 'A vibrant and refreshing blue-colored mocktail.', image: '/images/menu/SLOT-10/blue-lagoon.png' },
  { id: 160, name: 'Lassi', price: 99, category: 'Desserts, Curd & Beverages', description: 'A traditional yogurt-based drink, sweet and refreshing.', image: '/images/menu/SLOT-10/lassi.png' },
  { id: 161, name: 'Virgin Mojito', price: 99, category: 'Desserts, Curd & Beverages', description: 'A classic non-alcoholic mojito with mint and lime.', image: '/images/menu/SLOT-10/virgin-mohito.png' },
  { id: 162, name: 'Vanilla Shake', price: 99, category: 'Desserts, Curd & Beverages', description: 'A classic and creamy vanilla milkshake.', image: '/images/menu/SLOT-10/vanilla-shake.png' },
  { id: 163, name: 'Pina Colada', price: 99, category: 'Desserts, Curd & Beverages', description: 'A tropical and creamy drink with pineapple and coconut flavors.', image: '/images/menu/SLOT-10/pina-collada.png' },
  { id: 164, name: 'Payasam with Vermicelli', price: 109, category: 'Desserts, Curd & Beverages', description: 'A traditional South Indian pudding made with vermicelli and milk.', image: '/images/menu/SLOT-10/payasam-with-vermicilli.png' },
  { id: 165, name: 'Pineapple Sheera', price: 129, category: 'Desserts, Curd & Beverages', description: 'A sweet and delicious semolina pudding with pineapple.', image: '/images/menu/SLOT-10/pineapple-sheera.png' },
  { id: 166, name: 'Strawberry Shake', price: 129, category: 'Desserts, Curd & Beverages', description: 'A refreshing milkshake made with fresh strawberries.', image: '/images/menu/SLOT-10/strawberry-shake.png' },
  { id: 167, name: 'Banana Shake', price: 129, category: 'Desserts, Curd & Beverages', description: 'A healthy and creamy milkshake made with ripe bananas.', image: '/images/menu/SLOT-10/banana-shake.png' },
  { id: 168, name: 'Kesari Bhaat', price: 139, category: 'Desserts, Curd & Beverages', description: 'A sweet and aromatic semolina dessert flavored with saffron.', image: '/images/menu/SLOT-10/kesari-bhaat.png' },
  { id: 169, name: 'Chocolate Shake', price: 139, category: 'Desserts, Curd & Beverages', description: 'A rich and indulgent chocolate milkshake.', image: '/images/menu/SLOT-10/chocolate-shake.png' },
  { id: 170, name: 'Coconut Kesari Bhaat', price: 149, category: 'Desserts, Curd & Beverages', description: 'A flavorful variation of Kesari Bhaat with added coconut.', image: '/images/menu/SLOT-10/coconut-kesari-bhaat.png' },
  { id: 171, name: 'Oreo Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A delicious milkshake made with crushed Oreo cookies.', image: '/images/menu/SLOT-10/vanilla-shake.png' },
  { id: 172, name: 'Badam Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A rich and creamy milkshake flavored with almonds.', image: '/images/menu/SLOT-10/vanilla-shake.png' },
  { id: 173, name: 'Paan Shake', price: 149, category: 'Desserts, Curd & Beverages', description: 'A unique and refreshing milkshake with the flavor of betel leaves.', image: '/images/menu/SLOT-10/vanilla-shake.png' },
  { id: 174, name: 'Kitkat Shake', price: 169, category: 'Desserts, Curd & Beverages', description: 'A crunchy and delicious milkshake made with Kitkat chocolate bars.', image: '/images/menu/SLOT-10/chocolate-shake.png' },
  { id: 175, name: 'Mineral Water', price: 20, category: 'Desserts, Curd & Beverages', description: 'Chilled mineral water bottle. Price is as per MRP.', image: '/images/menu/SLOT-10/cocunut-water.png' },

  // Extras & Party Menu (SLOT 11)
  { id: 176, name: 'Podi Masala', price: 10, category: 'Extras & Party Menu', description: 'A flavorful spice powder to enhance your meal.', image: '/images/menu/SLOT-11/podi-masala.png' },
  { id: 178, name: 'Puri (2pcs)', price: 29, category: 'Extras & Party Menu', description: 'Two pieces of fluffy deep-fried bread.', image: '/images/menu/SLOT-11/puri-2pc.png' },
  { id: 179, name: 'Aloo Bhaji', price: 29, category: 'Extras & Party Menu', description: 'A simple and delicious potato curry side dish.', image: '/images/menu/SLOT-11/aloo-bhaji.png' },
  { id: 180, name: 'Thairu (Curd)', price: 29, category: 'Extras & Party Menu', description: 'A side of plain, refreshing yogurt.', image: '/images/menu/SLOT-11/Thairu(curd).png' },
  { id: 181, name: 'Cheese/Butter/Ghee', price: 30, category: 'Extras & Party Menu', description: 'An extra serving of cheese, butter, or ghee.', image: '/images/menu/SLOT-11/cheese-butter-ghee.png' },
];


export const GALLERY_IMAGES: string[] = [
  '/images/gallery/srivialli_1.png',
  '/images/gallery/srivalli_2.jpeg',
  '/images/gallery/srivalli_3.jpeg',
  '/images/gallery/srivalli_4.jpeg',
  '/images/gallery/srivalli_5.jpeg',
  '/images/gallery/srivalli_6.jpeg',
  '/images/gallery/srivalli_7.jpeg',
];

export const REVIEWS: Review[] = [
  {
    id: 1,
    author: 'Rajesh Kumar',
    quote: 'Best South Indian restaurant in Jaipur! The dosas are crispy and perfectly made. The sambhar and chutneys are authentic. Staff is very courteous. Highly recommended!',
    rating: 5,
    image: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=1A472A&color=fff&size=128',
    date: '2 weeks ago',
    platform: 'Google'
  },
  {
    id: 2,
    author: 'Priya Sharma',
    quote: 'Amazing food quality and taste! The Masala Dosa was outstanding. The ambiance is great and the service is quick. Will definitely visit again.',
    rating: 5,
    image: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=C06C58&color=fff&size=128',
    date: '3 weeks ago',
    platform: 'Google'
  },
  {
    id: 3,
    author: 'Amit Verma',
    quote: 'Authentic South Indian flavors in the heart of Jaipur. The filter coffee is a must-try! Loved the variety in the menu. Great value for money.',
    rating: 5,
    image: 'https://ui-avatars.com/api/?name=Amit+Verma&background=D4AF37&color=000&size=128',
    date: '1 month ago',
    platform: 'Google'
  },
  {
    id: 4,
    author: 'Neha Agarwal',
    quote: 'The idlis are so soft and fluffy! The uttapams are loaded with toppings. Everything was fresh and delicious. The staff is friendly and helpful.',
    rating: 5,
    image: 'https://ui-avatars.com/api/?name=Neha+Agarwal&background=F4C430&color=000&size=128',
    date: '1 month ago',
    platform: 'Google'
  },
  {
    id: 5,
    author: 'Vikram Singh',
    quote: 'Excellent food and service! The Srivalli Special Dosa is amazing. Clean and hygienic place. Perfect spot for South Indian cuisine lovers.',
    rating: 4,
    image: 'https://ui-avatars.com/api/?name=Vikram+Singh&background=1A472A&color=fff&size=128',
    date: '2 months ago',
    platform: 'Google'
  },
  {
    id: 6,
    author: 'Anjali Joshi',
    quote: 'Great place for breakfast and dinner. The variety of dosas is impressive. The taste takes me back to Chennai. Reasonable prices and good portion sizes.',
    rating: 5,
    image: 'https://ui-avatars.com/api/?name=Anjali+Joshi&background=C06C58&color=fff&size=128',
    date: '2 months ago',
    platform: 'Google'
  },
];

export const HERO_IMAGE = '/images/srivalli_landing_page.png';
export const ABOUT_IMAGE = '/images/hero/about.jpg';

// Google Maps Review Link - Replace with actual Srivalli restaurant Google Maps link
export const GOOGLE_MAPS_REVIEW_URL = 'https://www.google.com/maps/search/?api=1&query=Srivalli+Restaurant+Jaipur';
export const GOOGLE_MAPS_PLACE_URL = 'https://maps.app.goo.gl/5nnxgfhMJdKB4YsE7'; // Replace with actual place URL
